builds:
  - binary: php-fpm_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

dockers:
  - image_templates:
      - "peopleperhour/php-fpm_exporter:latest"
    build_flag_templates:
      - "--build-arg=VERSION=pph"

archive:
  format: binary
